sudo: required

env:
  global:
    - PROJECT_NAME=multipl
    - DOCKER_IMAGE_NAME=mailgun

language: node_js
node_js:
  - "10"

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
  - docker

before_script:
  - yarn
  - yarn lint
  - yarn test --coverage

script:
  - make build

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash >/dev/null; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - git clone https://github.com/multipl/MANAGE
  - ./MANAGE/gcloud/auth.sh

deploy:
  - provider: script
    script: ./MANAGE/gcloud/push.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./MANAGE/gcloud/push-tag.sh
    skip_cleanup: true
    on:
      tags: true

notifications:
  slack:
    secure: "TNIpFPF++xp/fHTEnj5/2lrCJPatcne+l1MkOEZ+0/Febxn4KE75oaBFG2z/d/MGKs2ej3bIOn9rDLedGjjpY9nazDvjlSIukVrDlBE+tyydQ0Qz0GOYH0+nIhOTDcii/ucj4ahm2oebJ50mPrN/seMPGaQ6lFpGxfGNYzEtSLsTnHB5dXUsGCrrg6bUVMoiW/erAdocoCbeEbVfVEeige/swrAqojbOpIcEK3JgPGhpIpkABGZGrDja6TPbpOG7WiNyvpAelOb1LPHdcBlsQH7oCMbUQrUX/3tXUwGnCXmnMprqp8zD7I2gB4mBcVBvO2qNjl6JZAw8LITks0QU2TEy/iFNKuA26YzkmWJmTK6NR45iHrRGNYXH1vxK8OKR41zG9p9NcGwXgaooXi4YI3trL7Jor8c5Sd5v4ZN5Q3LdrbLFOS/l0uo5rJQv97gzPMgM2qewOuUP/k061PfJfsZUKpJ9cncuqlGe8ZLMzNqY+H82s1X+SSNls8GiXkKDcD6XSrtsu7H0H7q0uzovSF5fymaJf24WMjr3Q9ztwXARNVT++KG9G931F5+eOTKmdPFucxOhqJ2mQEb5lQoRZ/vBgkggkF/JlNaZfnuAPvusV1EAwBuwiQKG69QL4D36K30YG31KjkRCYfjpAxTBF4+SyKCwyr7Q+LKRIGLEVrc="
